name: Cypress E2E tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          USER_TEST_EMAIL: ${{ secrets.USER_TEST_EMAIL }}
          USER_TEST_PASSWORD: ${{ secrets.USER_TEST_PASSWORD }}
          API_URL: ${{ secrets.API_URL }}
